---

- hosts: all
  become: true
  tasks:
    - name: update_cache index page
      apt:
        update_cache: yes
      when: ansible_distribution == "ubuntu"

    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "ubuntu"

    - name: add php support for apache2
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "ubuntu"




