---

- hosts: webservers
  become: true
  pre_tasks:
    - name: install updates for ubuntu
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
        state: latest
      when: ansible_distribution == "ubuntu"

    - name: install database-server
      tags: ubuntu,database,mariadb-server
      apt: 
        name: 
          - mariadb-server
          - samba
          - nginx
        state: latest

    - name: copying default html site
      tags: ubuntu,database,mariadb-server,nginx
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      #when: ansible_distribution == "ubuntu"
 






